addSbtPlugin("org.scala-js"      % "sbt-scalajs"         % "1.11.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler" % "0.21.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.9.0")
